### ISSUE TITLE
ToDo's for v0.4 or higher: new add-on ideas

### ISSUE THREAD

**Issue by ShadowCreator250** [ShadowCreator250/VanillaMods#6]
- [ ] vertical elevators (like in ftb infinity)
- [ ] oreminer: mines whole ore veins 
- [ ] miningturtle: mines a tunnel and collects all items
- [ ] excavator: a tool for landscaping, mining tunnels, ... (like in ftb infinity)
- [X] blockbreaker: breaks all surrounding blocks (on the eye level)
- [X] autofields: automatic harvesting fields
- [X] lumberaxe: chops whole trees
